### ISSUE TITLE
Segmentation fault for BMFTools err

### ISSUE THREAD

**Issue by cmkrueger17** [ARUP-NGS/BMFtools#97] opened 2017-03-17 22:31 UTC
Hey Daniel,
I am getting a segmentation fault for this one bam file. I've run BMFTools err hundreds of times on other bams with no issues, but for some reason even if I downsample the bam to 100 lines I still get the "segmentation fault (core dumped)" error and I am lost. Do you think you have some time to look at this?

bmftools err main /Reference/local_reference/Data/PhiX/human_g1k_v37_decoy_phiXAdaptr.fasta ./downsampled.bam -c ./phiXtable.txt -g ./BMFgloberror.tsv

I could email you the bam file (its only 94K).

@BrettKennedy @dnbh 

Thanks!
-Chris

**Comment by dnbh** [comment] 2017-03-17 23:05
Can you upload the BAM and the fasta? That'd be awesome.

Thanks!

**Comment by cmkrueger17** [comment] 2017-03-18 16:14
@dnbh @BrettKennedy 
Unfortunately github doesn't accept bam or fasta file type uploads, so I've loaded the downsampled bam here: https://transfer.sh/hu69c/downsampled.bam
The reference fasta is 3 gb, but it's the phix fasta file. Do you need that too?

**Comment by dnbh** [comment] 2017-03-18 17:19
Can you upload a gzip archive somewhere?

**Comment by cmkrueger17** [comment] 2017-03-18 20:52
@dnbh 
Here is the reference fasta: https://transfer.sh/m9KQe/human-g1k-v37-decoy-phixadaptr.fasta.gz

FYI, I ran BamUtils "validate" on the troublesome BAM file and got this:

_ERROR: Poorly formatted tag in header: :CN:ARUP
ERROR: Poorly formatted tag in header: :PU:PhiX
1 invalid SAM/BAM Header lines were skipped due to:
SAM/BAM Header line failed to store RG record.


Number of records read = 200423
Number of valid records = 200423

TotalReads	200423.00
MappedReads	198137.00
PairedReads	200423.00
ProperPair	192972.00
DuplicateReads	0.00
QCFailureReads	0.00

MappingRate(%)	98.86
PairedReads(%)	100.00
ProperPair(%)	96.28
DupRate(%)	0.00
QCFailRate(%)	0.00

TotalBases	20016804.00
BasesInMappedReads	19788204.00
Returning: 0 (SUCCESS)_



Very odd how that got in the bam file

**Comment by dnbh** [comment] 2017-03-18 22:12
Your bwa command has 2 extra ":"s before "CN" and "PU", respectively, which explains the warning message. (-R@RG\tID:PhiX\tPL:ILLUMINA\tLB:PhiX\tSM:PhiX\t:CN:ARUP\t:PU:PhiX)

I ran it with a current version of bmftools and have normal-looking output. What release/commit are you using?

```
#Cycle  Read 1 Error Rate   Read 2 Error Rate   Read 1 Error Count  Read 1 Obs Count    Read 2 Error Count  Read 2 Obs Count
1   0.008908685969  0.004504504505  4   449 2   444 
2   0.000000000000  0.004504504505  0   449 2   444 
3   0.000000000000  0.002247191011  0   449 1   445 
4   0.004454342984  0.002247191011  2   449 1   445 
5   0.002227171492  0.006726457399  1   449 3   446 
6   0.000000000000  0.000000000000  0   450 0   446 
7   0.000000000000  0.000000000000  0   450 0   446 
8   0.000000000000  0.008968609865  0   450 4   446 
9   0.004444444444  0.002242152466  2   450 1   446 
10  0.000000000000  0.008968609865  0   450 4   446 
11  0.002222222222  0.002247191011  1   450 1   445 
```

```
##Parameters: minFM 0. maxFM 2147483647.Duplex required: False
#Global Error Rates 0.002125184556  0.004599732626
#Global Sum/Count   95/44702    203/44133
```

**Comment by dnbh** [comment] 2017-03-18 22:18
Hi Chris,

This issue was resolved in https://github.com/ARUP-NGS/BMFtools/issues/91.

**Comment by BrettKennedy** [comment] 2017-03-21 18:25
Hey Daniel, thanks for looking into this a bit.  I closed #91 because it appeared to be an isolated issue with that run and I was unable to reproduce it with any other dataset, but now it appears it may be a more persistent problem.  Of the runs he tested, this is the only one from the HiSeq in high output mode, which I think bins the quality scores, so this maybe related to that.  He's going to check with another high output run to see if the problem is specific to that sequencer in that mode.

**Comment by dnbh** [comment] 2017-03-22 05:40
I've been unable to reproduce it with a current build of bmftools, but I was able to with the 1.0 release.

Chris, can you try a more recent version?

**Comment by BrettKennedy** [comment] 2017-03-22 16:20
We had thought we were working with the most recent version, but you were correct, it was out of date.  Pulling down a fresh copy and running with that worked just fine.  Thanks for your help.  I'm closing this issue.

**Closed by BrettKennedy** 2017-03-22 16:20 UTC
